HOST = 'https://github.com'
BASE_REPO_OWNER = 'Infineon'
REPO_NAME = 'deepcraft-starter-models'
BASE_REPO = fr'{BASE_REPO_OWNER}/{REPO_NAME}'
BASE_REPO_URL = f'{HOST}/{BASE_REPO}.git'
MAIN_BRANCH = 'main'
GIT_DIR = '.git_deepcraft'